### ISSUE TITLE
Entrega 2 - 2.2.3 User Stories

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.2-Strix#10]
### Ajustar valor de negócio
- [x] Eu como personal, Quero adicionar uma aula, _Para lembrar-me mais tarde_.
- [x] Eu como personal, Quero editar uma aula registrada, _Para alterar algum dado_.
- [x] Eu, como usuário, desejo me autenticar no sistema com meu user e senha, _para poder utilizar das funcionalidades do sistema_.

### Ajustar user story:
- [x] Eu, como usuário, desejo remover ~~do sistema~~ um aluno previamente adicionado, para lidar com a desistência de alunos.
- [x] Eu, como usuário, desejo **criar** um novo exercício **e** **adicioná-lo** ~~ao sistema~~, para poder cadastrar os exercícios que eu enviarei aos alunos. (não pode ter duas ações, apenas uma)
- [x] Eu, como usuário, desejo editar os dados de um exercício, para poder **_acrescentar ou remover_** instruções. (não pode ter duas ações, apenas uma)

**Comment by beatrizSO** [comment]
Alterações necessárias realizadas.
