### ISSUE TITLE
Enterga 2 - Planejamento

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.2-Strix#2]
**Visão de Produto e Projeto**

- [x] o planejamento apresentado não está adequado aos itens de backlog de produto.  Não há nenhum item denominado CRUD. Devem ser informadas as histórias que farão parte de cada sprint.
- [x] sprint 3 apenas para a criação de protótipo?! Não é adequado ao desenvolvimento ágil.

**Comment by beatrizSO** [comment]
Ajustes realizados.
