### ISSUE TITLE
Entrega 1 e 2 - Lições aprendidas

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.2-Strix#6]
**Visão de Produto e Projeto**
 - Lições aprendidas: a equipe não apresenta nenhum relato adequado O que a equipe aprendeu? em que situação ocorreu o aprendizado? quais os benefícios percebidos pela equipe, desse aprendizado? etc.

**Comment by beatrizSO** [comment]
ajuste realizado.
